@host=http://localhost:5000/v1

GET {{host}}/posts/categories/3 HTTP/1.1

###

POST {{host}}/categories HTTP/1.1
content-type: application/json

{
    "route": "/autre",
    "label": "Autre"
}

### Ajout d'un nouveau post
POST {{host}}/posts
Content-Type: application/json

{
    "slug": 123,
    "title": "testing23",
    "excerpt": "testing",
    "content": "testing",
    "category_id": "3"
}